### ISSUE TITLE
make gh-pages the default branch

### ISSUE THREAD

**Issue by aaren** [swcarpentry/python-intermediate-mosquitoes#1]
This repo was created with a `master` branch as default but needs to have `gh-pages` as default to be consistent with the lesson-template. I have created the `gh-pages` branch as a copy of `master` and the `master` branch now needs deleting.

@gvwilson can you delete the `master` branch and set `gh-pages` as the default? I don't have permission to do this.

**Comment by gvwilson** [comment]
Done.
