### ISSUE TITLE
Filenames in 01-intro-python.md don't match what's in data directory.

### ISSUE THREAD

**Issue by jrsmith3** [swcarpentry/python-intermediate-mosquitoes#6]
The first example occurs at line 61:

``` markdown
pandas.read_csv('mosquito_data_A1.csv')
```

The file `mosquito_data_A1.csv` does not exist in the `data` subdirectory, but the file `A1_mosquito_data.csv` does. I suspect there was a typo somewhere.

**Comment by tbekolay** [comment]
#5's been merged, so this should be fixed now. Don't hesitate to reopen this issue if it's not actually fixed!

**Comment by jrsmith3** [comment]
Merging PR #5 closes this issue. Thanks for closing all these issues and merging all the PRs!
